### ISSUE TITLE
unicode字符支持

### ISSUE THREAD

**Issue by codehz** [covscript/covscript-darwin#2]
![image](https://user-images.githubusercontent.com/13158903/37745327-32936586-2daf-11e8-82ef-5eeb45b37887.png)
内容为中文字符和unicode有效字符，具体来说是这些（节选
```
测试
𝐀𝐁𝐂𝐃𝐄𝐅𝐆𝐇𝐈𝐉𝐊𝐋𝐌𝐍𝐎𝐏𝐐𝐑𝐒𝐓𝐔𝐕𝐖𝐗𝐘𝐙
𝔸𝔹𝔻𝔼𝔽𝔾𝕀𝕁𝕂𝕃𝕄𝕆𝕊𝕋𝕌𝕍𝕎𝕏𝕐𝕑
𝝖𝝗𝝘𝝙𝝚𝝛𝝜𝝝𝝞𝝟𝝠𝝡𝝢𝝣𝝤𝝥𝝦𝝧𝝨𝝩𝝪𝝫𝝬𝝭𝝮𝝯
```

**Comment by mikecovlee** [comment]
Darwin从原理上就无法支持Unicode，这个是无奈之举
